# Generated by Django 2.2.5 on 2019-11-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('imdb', models.TextField()),
                ('date', models.TextField()),
                ('rate', models.TextField()),
                ('platform', models.TextField(default='[]')),
                ('companies', models.TextField(default='[]')),
                ('vcount', models.IntegerField()),
                ('v_average', models.TextField()),
                ('language', models.TextField()),
                ('popularity', models.TextField()),
                ('overview', models.TextField()),
            ],
        ),
    ]
