# Generated by Django 2.2.5 on 2019-11-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_link',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
