# Generated by Django 2.2.5 on 2019-11-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20191110_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
