# Generated by Django 2.2.5 on 2019-11-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_movie_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='comment_lists',
            field=models.TextField(default='crawler/resources/<django.db.models.fields.AutoField>.jpg'),
        ),
    ]
