# Generated by Django 2.2.5 on 2019-11-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_movie_comment_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.TextField(default=''),
        ),
    ]
