# Generated by Django 2.2.5 on 2019-11-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_movie_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(default='NewPage')),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
    ]
