# Generated by Django 2.2.5 on 2019-11-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_time',
            field=models.IntegerField(default=0),
        ),
    ]
