# Generated by Django 2.2.5 on 2019-11-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.TextField(default='')),
            ],
        ),
    ]
