# Generated by Django 2.2.5 on 2019-11-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0010_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast_image',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='casts',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_score',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='rate_data',
            field=models.TextField(default=''),
        ),
    ]
