# Generated by Django 2.2.5 on 2019-11-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0011_auto_20191114_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platform',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
