# Generated by Django 2.2.5 on 2019-11-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0012_auto_20191114_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='allBetterPercentage',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='genreBetterPercentage',
            field=models.TextField(default=''),
        ),
    ]
